### PR TITLE
Interface portchannel configuration was not correctly updating

### PR DESCRIPTION
**Pull request by asaenz**

### CODE REVIEW

**Comment by logankimmel** [comment]
:shipit:

**Comment by asaenz** [comment]
Still need some testing on this...

**Comment by asaenz** [comment]
This is going to require a 2nd review, I added another commit to fix another issue that sprung up.  Please review again, but this is good to go once approved.

**Comment by aimers1975** [comment]
@logankimmel Can you take care of this review and let me know...This jira is blocking.

**Comment by logankimmel** [comment]
👍

**Pull request merged**
