### PR TITLE
fix force_interface exists? method

### PR DESCRIPTION
**Pull request by gavin-scott**
Accept port names like "Te 0/3" in the exists? method.

### CODE REVIEW

**Comment by gavin-scott** [comment]
@logankimmel FYI I had some success with this change. Needs to be improved to add unit tests for the exists? method.

While looking through the code I also have some concerns with this:

https://github.com/dell-asm/dell-force10/blob/148949fb2e7f341b9560bf8af6eea1a617d62dd7/lib/puppet/provider/force10_interface/dell_ftos.rb#L79

    port = iface.split('/')[1]

I believe the above will take an interface like "Tengigabitethernet0/1" and considers the port to be "1". But it is possible in some cases to get something like "Tengigabitethernet3/1" which would mean something like port 1 on chassis 3. So we really need to be considering both numbers.

**Comment by logankimmel** [comment]
@gavin-scott @ripienaar This looks like it should fix the issue with the resource name

**Comment by gavin-scott** [comment]
@sushilrai or @ripienaar can you review? @logankimmel will address the port number comment separately.

**Comment by gavin-scott** [comment]
This was pulled into a PR that @logankimmel submitted, closing.

**Pull request closed without merging**
