### PR TITLE
added snmp community command to get community strings 

### PR DESCRIPTION
**Pull request by arunrordell**
added snmp community string command to get all the community strings and converts result  to json.

test output:
 "snmp_community_string":"[\"private\",\"public\"]"

### CODE REVIEW

**Comment by ripienaar** [comment]
Are we just going by convention that the private community is the first one and 2nd is public? a hash would make more sense to me I think?

**Comment by arunrordell** [comment]
It is just based on the result from the device. The result from the device is 

Env11_S4810_Top#show snmp community
Community: private
Context: None
Security-name: v1v2cwriteu

Community: public
Context: None
Security-name: v1v2cwriteu

we only need to check if a community string is correct or not for authentication.I think array will take care of that. @ripienaar

**Comment by ripienaar** [comment]
It could be useful down the line to have the distinction so probably not a big step to add?

If you add here please also add to asm-deployer Privider::Force10 in the list of JSON facts

**Comment by arunrordell** [comment]
so should I make it to hash having index as key for each community string?

**Comment by ripienaar** [comment]
Yes '{"public": "public_community_string" .....}'

**Comment by arunrordell** [comment]
I think it wont work if there is same community string for read and read/write. I managed to make the hash as follows. 

"snmp_community_string":"{\"0\":\"private\",\"1\":\"public\"}

**Comment by ripienaar** [comment]
I am not sure I understand, why cant you put "private" instead of "0"? that way when we want the private string we can just do `facts["snmp_community_string"]["private"]` and we get the answer.

Can you explain why that's not possible?

**Comment by arunrordell** [comment]
image

I think private is the actual community string that we need to verify if it is corrects or not. if we create the string as key. how can i use that to retrieve the actual string. as of now I verifying it as follows in nagios module 

 facts_for_device=ASM::PrivateUtil.facts_find(device_cert_name)
	   strings_in_json= facts_for_device['snmp_community_string']
	   community_strings=JSON.parse(strings_in_json)
	   if community_strings.nil? || community_strings.include?(community_string)
	   return true

**Comment by ripienaar** [comment]
Oh right I see it supports more than just 2 keys which some support - typically they tend to only support a "public" and a "private" comunity - and those would have different values that's kind of a like password to get public data of private data (which includes writing)

but these seems more complex, so a Array is probably best for now till we figure out a actual use, sorry for the wild goose chase

**Comment by arunrordell** [comment]
Ok I will do the same thing for other devices also.

**Comment by gavin-scott** [comment]
:+1:

**Pull request closed without merging**
